// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarBlog.Data;

#nullable disable

namespace StarBlog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250417080714_MoreVisitStats")]
    partial class MoreVisitStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.18");

            modelBuilder.Entity("StarBlog.Data.Models.VisitRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<string>("Isp")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("isp");

                    b.Property<string>("Province")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("province");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("referrer");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("region_code");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_path");

                    b.Property<string>("RequestQueryString")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_query_string");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_visit_record");

                    b.HasIndex("City")
                        .HasDatabaseName("idx_visit_city");

                    b.HasIndex("Country")
                        .HasDatabaseName("idx_visit_country");

                    b.HasIndex("Isp")
                        .HasDatabaseName("idx_visit_isp");

                    b.HasIndex("Province")
                        .HasDatabaseName("idx_visit_province");

                    b.HasIndex("RegionCode")
                        .HasDatabaseName("idx_visit_region_code");

                    b.HasIndex("RequestPath")
                        .HasDatabaseName("idx_visit_path");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("idx_visit_status");

                    b.HasIndex("Time")
                        .HasDatabaseName("idx_visit_time");

                    b.HasIndex("Time", "StatusCode")
                        .HasDatabaseName("idx_visit_time_status");

                    b.ToTable("visit_record", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
