// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarBlog.Data;

#nullable disable

namespace StarBlog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.18");

            modelBuilder.Entity("StarBlog.Data.Models.VisitRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("referrer");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_path");

                    b.Property<string>("RequestQueryString")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_query_string");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_visit_record");

                    b.HasIndex("RequestPath")
                        .HasDatabaseName("idx_visit_path");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("idx_visit_status");

                    b.HasIndex("Time")
                        .HasDatabaseName("idx_visit_time");

                    b.HasIndex("Time", "StatusCode")
                        .HasDatabaseName("idx_visit_time_status");

                    b.ToTable("visit_record", (string)null);
                });

            modelBuilder.Entity("StarBlog.Data.Models.VisitRecord", b =>
                {
                    b.OwnsOne("StarBlog.Data.Models.IpInfo", "IpInfo", b1 =>
                        {
                            b1.Property<long>("VisitRecordId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_country");

                            b1.Property<string>("Isp")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_isp");

                            b1.Property<string>("Province")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_province");

                            b1.Property<string>("RegionCode")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_region_code");

                            b1.HasKey("VisitRecordId");

                            b1.ToTable("visit_record");

                            b1.WithOwner()
                                .HasForeignKey("VisitRecordId")
                                .HasConstraintName("fk_visit_record_visit_record_id");
                        });

                    b.OwnsOne("StarBlog.Data.Models.UserAgentInfo", "UserAgentInfo", b1 =>
                        {
                            b1.Property<long>("VisitRecordId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.HasKey("VisitRecordId");

                            b1.ToTable("visit_record");

                            b1.WithOwner()
                                .HasForeignKey("VisitRecordId")
                                .HasConstraintName("fk_visit_record_visit_record_id");

                            b1.OwnsOne("StarBlog.Data.Models.Device", "Device", b2 =>
                                {
                                    b2.Property<long>("UserAgentInfoVisitRecordId")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("id");

                                    b2.Property<string>("Brand")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_device_brand");

                                    b2.Property<string>("Family")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_device_family");

                                    b2.Property<bool>("IsSpider")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("user_agent_info_device_is_spider");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_device_model");

                                    b2.HasKey("UserAgentInfoVisitRecordId");

                                    b2.ToTable("visit_record");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAgentInfoVisitRecordId")
                                        .HasConstraintName("fk_visit_record_visit_record_id");
                                });

                            b1.OwnsOne("StarBlog.Data.Models.OS", "OS", b2 =>
                                {
                                    b2.Property<long>("UserAgentInfoVisitRecordId")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("id");

                                    b2.Property<string>("Family")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_family");

                                    b2.Property<string>("Major")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_major");

                                    b2.Property<string>("Minor")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_minor");

                                    b2.Property<string>("Patch")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_patch");

                                    b2.Property<string>("PatchMinor")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_patch_minor");

                                    b2.HasKey("UserAgentInfoVisitRecordId");

                                    b2.ToTable("visit_record");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAgentInfoVisitRecordId")
                                        .HasConstraintName("fk_visit_record_visit_record_id");
                                });

                            b1.OwnsOne("StarBlog.Data.Models.UserAgent", "UserAgent", b2 =>
                                {
                                    b2.Property<long>("UserAgentInfoVisitRecordId")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("id");

                                    b2.Property<string>("Family")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_user_agent_family");

                                    b2.Property<string>("Major")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_user_agent_major");

                                    b2.Property<string>("Minor")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_user_agent_minor");

                                    b2.Property<string>("Patch")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_user_agent_patch");

                                    b2.HasKey("UserAgentInfoVisitRecordId");

                                    b2.ToTable("visit_record");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAgentInfoVisitRecordId")
                                        .HasConstraintName("fk_visit_record_visit_record_id");
                                });

                            b1.Navigation("Device")
                                .IsRequired();

                            b1.Navigation("OS")
                                .IsRequired();

                            b1.Navigation("UserAgent")
                                .IsRequired();
                        });

                    b.Navigation("IpInfo")
                        .IsRequired();

                    b.Navigation("UserAgentInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
