// <auto-generated />

using System;
using Ip2RegionDataProc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ip2RegionDataProc.src.Data.Migrations {
    [DbContext(typeof(AppDbContext))]
    [Migration("20250319074535_InitialCreate")]
    partial class InitialCreate {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("Ip2RegionDataProc.Data.Models.AuditLog", b => {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("Changes")
                    .HasColumnType("TEXT")
                    .HasColumnName("changes");

                b.Property<string>("CurrentValues")
                    .HasColumnType("TEXT")
                    .HasColumnName("current_values");

                b.Property<string>("Description")
                    .HasColumnType("TEXT")
                    .HasColumnName("description");

                b.Property<string>("EntityId")
                    .HasColumnType("TEXT")
                    .HasColumnName("entity_id");

                b.Property<string>("EntityName")
                    .HasColumnType("TEXT")
                    .HasColumnName("entity_name");

                b.Property<Guid>("EventId")
                    .HasColumnType("TEXT")
                    .HasColumnName("event_id");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("event_type");

                b.Property<string>("OriginalValues")
                    .HasColumnType("TEXT")
                    .HasColumnName("original_values");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("TEXT")
                    .HasColumnName("timestamp");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("username");

                b.HasKey("Id")
                    .HasName("pk_audit_logs");

                b.ToTable("audit_logs", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}