services:
  starblog:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: starblog
    restart: unless-stopped
    ports:
      - "5038:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Data Source=/app/data/app.db
    volumes:
      - starblog-data:/app/data

volumes:
  starblog-data:
