<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\StarBlog.Infrastructure\StarBlog.Infrastructure.csproj" />
        <ProjectReference Include="..\StarBlog.Data\StarBlog.Data.csproj" />
        <ProjectReference Include="..\StarBlog.Content\StarBlog.Content.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
        <PackageReference Include="CodeLab.Share" Version="1.4.2" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.AI" Version="9.8.0" />
        <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="9.8.0-preview.1.25412.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" Version="10.7.1" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.13.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.0" />
        <PackageReference Include="UAParser" Version="3.1.47" />
        <PackageReference Include="X.PagedList" Version="10.5.9" />
    </ItemGroup>

</Project>
