// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarBlog.Api.Infrastructure.Persistence;

#nullable disable

namespace StarBlog.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StarBlogDbContext))]
    [Migration("20260820110115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("StarBlog.Api.Modules.Analytics.Domain.VisitRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("referrer");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_path");

                    b.Property<string>("RequestQueryString")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_query_string");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_visit_record");

                    b.HasIndex("RequestPath")
                        .HasDatabaseName("idx_visit_path");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("idx_visit_status");

                    b.HasIndex("Time")
                        .HasDatabaseName("idx_visit_time");

                    b.HasIndex("Time", "StatusCode")
                        .HasDatabaseName("idx_visit_time_status");

                    b.ToTable("visit_record", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Comments.Domain.AnonymousUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_time");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_anonymous_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_anonymous_user_email");

                    b.ToTable("anonymous_user", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Comments.Domain.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("anonymous_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_time");

                    b.Property<bool>("IsNeedAudit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_need_audit");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("post_id");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_time");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<bool>("Visible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("AnonymousUserId")
                        .HasDatabaseName("ix_comment_anonymous_user_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_comment_parent_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_comment_post_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Configuration.Domain.ConfigItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_config");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_config_key");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<bool>("Visible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.FeaturedCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("IconCssClass")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_css_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_featured_category");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_featured_category_category_id");

                    b.ToTable("featured_category", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.FeaturedPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_featured_post");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasDatabaseName("ix_featured_post_post_id");

                    b.ToTable("featured_post", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("creation_time");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_publish");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_update_time");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("Slug")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_post");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_post_category_id");

                    b.HasIndex("IsPublish")
                        .HasDatabaseName("ix_post_is_publish");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_post_slug")
                        .HasFilter("slug IS NOT NULL");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.PostPublication", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("creation_time");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_url");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_update_time");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER")
                        .HasColumnName("platform");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("PublishedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_time");

                    b.Property<string>("RenderedContent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rendered_content");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_post_publication");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_publication_post_id");

                    b.ToTable("post_publication", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.PostTranslation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("creation_time");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_update_time");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("post_id");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_post_translation");

                    b.HasIndex("PostId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_post_translation_post_id_language");

                    b.ToTable("post_translation", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.PublicationChannel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_id");

                    b.Property<string>("AppSecret")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("app_secret");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("creation_time");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_update_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER")
                        .HasColumnName("platform");

                    b.Property<string>("PublishUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("publish_url");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT")
                        .HasColumnName("theme");

                    b.HasKey("Id")
                        .HasName("pk_publication_channel");

                    b.ToTable("publication_channel", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.TopPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_top_post");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasDatabaseName("ix_top_post_post_id");

                    b.ToTable("top_post", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Identity.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_name");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Links.Domain.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<bool>("Visible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_link");

                    b.ToTable("link", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Links.Domain.LinkExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ApplyTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("apply_time");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("verified");

                    b.Property<string>("WebMaster")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("web_master");

                    b.HasKey("Id")
                        .HasName("pk_link_exchange");

                    b.HasIndex("Url")
                        .HasDatabaseName("ix_link_exchange_url");

                    b.ToTable("link_exchange", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Media.Domain.FeaturedPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_id");

                    b.HasKey("Id")
                        .HasName("pk_featured_photo");

                    b.HasIndex("PhotoId")
                        .IsUnique()
                        .HasDatabaseName("ix_featured_photo_photo_id");

                    b.ToTable("featured_photo", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Media.Domain.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<long>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_photo");

                    b.ToTable("photo", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Notifications.Domain.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("dedup_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_dedup_key")
                        .HasFilter("dedup_key IS NOT NULL");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_message_status_next_attempt_at");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Analytics.Domain.VisitRecord", b =>
                {
                    b.OwnsOne("StarBlog.Api.Modules.Analytics.Domain.IpInfo", "IpInfo", b1 =>
                        {
                            b1.Property<long>("VisitRecordId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_country");

                            b1.Property<string>("Isp")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_isp");

                            b1.Property<string>("Province")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_province");

                            b1.Property<string>("RegionCode")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("ip_info_region_code");

                            b1.HasKey("VisitRecordId");

                            b1.ToTable("visit_record");

                            b1.WithOwner()
                                .HasForeignKey("VisitRecordId")
                                .HasConstraintName("fk_visit_record_visit_record_id");
                        });

                    b.OwnsOne("StarBlog.Api.Modules.Analytics.Domain.UserAgentInfo", "UserAgentInfo", b1 =>
                        {
                            b1.Property<long>("VisitRecordId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.HasKey("VisitRecordId");

                            b1.ToTable("visit_record");

                            b1.WithOwner()
                                .HasForeignKey("VisitRecordId")
                                .HasConstraintName("fk_visit_record_visit_record_id");

                            b1.OwnsOne("StarBlog.Api.Modules.Analytics.Domain.AgentInfo", "UserAgent", b2 =>
                                {
                                    b2.Property<long>("UserAgentInfoVisitRecordId")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("id");

                                    b2.Property<string>("Family")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_user_agent_family");

                                    b2.Property<string>("Major")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_user_agent_major");

                                    b2.Property<string>("Minor")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_user_agent_minor");

                                    b2.Property<string>("Patch")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_user_agent_patch");

                                    b2.HasKey("UserAgentInfoVisitRecordId");

                                    b2.ToTable("visit_record");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAgentInfoVisitRecordId")
                                        .HasConstraintName("fk_visit_record_visit_record_id");
                                });

                            b1.OwnsOne("StarBlog.Api.Modules.Analytics.Domain.DeviceInfo", "Device", b2 =>
                                {
                                    b2.Property<long>("UserAgentInfoVisitRecordId")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("id");

                                    b2.Property<string>("Brand")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_device_brand");

                                    b2.Property<string>("Family")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_device_family");

                                    b2.Property<bool>("IsSpider")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("user_agent_info_device_is_spider");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_device_model");

                                    b2.HasKey("UserAgentInfoVisitRecordId");

                                    b2.ToTable("visit_record");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAgentInfoVisitRecordId")
                                        .HasConstraintName("fk_visit_record_visit_record_id");
                                });

                            b1.OwnsOne("StarBlog.Api.Modules.Analytics.Domain.OsInfo", "OS", b2 =>
                                {
                                    b2.Property<long>("UserAgentInfoVisitRecordId")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("id");

                                    b2.Property<string>("Family")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_family");

                                    b2.Property<string>("Major")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_major");

                                    b2.Property<string>("Minor")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_minor");

                                    b2.Property<string>("Patch")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_patch");

                                    b2.Property<string>("PatchMinor")
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("user_agent_info_os_patch_minor");

                                    b2.HasKey("UserAgentInfoVisitRecordId");

                                    b2.ToTable("visit_record");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAgentInfoVisitRecordId")
                                        .HasConstraintName("fk_visit_record_visit_record_id");
                                });

                            b1.Navigation("Device")
                                .IsRequired();

                            b1.Navigation("OS")
                                .IsRequired();

                            b1.Navigation("UserAgent")
                                .IsRequired();
                        });

                    b.Navigation("IpInfo")
                        .IsRequired();

                    b.Navigation("UserAgentInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Comments.Domain.Comment", b =>
                {
                    b.HasOne("StarBlog.Api.Modules.Comments.Domain.AnonymousUser", "AnonymousUser")
                        .WithMany()
                        .HasForeignKey("AnonymousUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_comment_anonymous_user_anonymous_user_id");

                    b.HasOne("StarBlog.Api.Modules.Comments.Domain.Comment", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comment_comment_parent_id");

                    b.Navigation("AnonymousUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.FeaturedCategory", b =>
                {
                    b.HasOne("StarBlog.Api.Modules.Content.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_featured_category_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.FeaturedPost", b =>
                {
                    b.HasOne("StarBlog.Api.Modules.Content.Domain.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_featured_post_posts_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.Post", b =>
                {
                    b.HasOne("StarBlog.Api.Modules.Content.Domain.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.PostTranslation", b =>
                {
                    b.HasOne("StarBlog.Api.Modules.Content.Domain.Post", "Post")
                        .WithMany("Translations")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_translation_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.TopPost", b =>
                {
                    b.HasOne("StarBlog.Api.Modules.Content.Domain.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_top_post_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Media.Domain.FeaturedPhoto", b =>
                {
                    b.HasOne("StarBlog.Api.Modules.Media.Domain.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_featured_photo_photos_photo_id");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Comments.Domain.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("StarBlog.Api.Modules.Content.Domain.Post", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
