name: tests

on:
  push:
  pull_request:

jobs:
  dotnet-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore StarBlog.slnx

      - name: Test (with coverage)
        run: dotnet test StarBlog.slnx -c Release --collect:"XPlat Code Coverage" --settings tests/coverlet.runsettings --results-directory TestResults

      - name: Upload TestResults
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
